name: Playwright Tests

on:
  #push:
  #  branches: 
  #      - main
  #      - master
  #      - develop
  #pull_request:
  #  branches: 
  #      - main
  #      - master
  #      - develop
  schedule:
    - cron: "0 13 * * *" # Runs at 13:00 UTC (8 AM EST)
  workflow_dispatch:

jobs:
  # Set up test job
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest  # Virtual Machine (macos-latest, windows-latest, ubuntu-latest etc.)
    permissions:
      contents: write

    # Set up NodeJS version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright Chromium Browser 
      - name: Install Playwright Chrome
        run: npx playwright install --with-deps chromium

      # configuring environment variables Example:
      - name: Configure environment variables from secrets
        run: |
          echo "Name=${{ secrets.NAME }}" >> .env

      # Running tests with Playwright 
      - name: Run Playwright tests
        run: npm run tests

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/
          retention-days: 30

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30


      # Deploying to GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./playwright-report